--
-- PostgreSQL database dump
--

\restrict FNMjS8MMCePrYgKwqJNS658sGBmFC8JdejSZQ5OUtZ22oECrSUm5XJ3ZKQJPSI6

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-05-04 15:48:43

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 16389)
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- TOC entry 6204 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 232 (class 1259 OID 17512)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 17511)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 17522)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 17521)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 17502)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 17501)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 17531)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 17550)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 17549)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 17530)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 17559)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 17558)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 261 (class 1259 OID 25815)
-- Name: cuahang_chitietdonhang; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuahang_chitietdonhang (
    id bigint NOT NULL,
    so_luong integer NOT NULL,
    don_hang_id bigint NOT NULL,
    san_pham_id bigint NOT NULL,
    CONSTRAINT cuahang_chitietdonhang_so_luong_check CHECK ((so_luong >= 0))
);


ALTER TABLE public.cuahang_chitietdonhang OWNER TO postgres;

--
-- TOC entry 260 (class 1259 OID 25814)
-- Name: cuahang_chitietdonhang_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cuahang_chitietdonhang ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuahang_chitietdonhang_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 265 (class 1259 OID 25853)
-- Name: cuahang_chitietphieunhap; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuahang_chitietphieunhap (
    id bigint NOT NULL,
    so_luong_nhap double precision NOT NULL,
    don_gia numeric(12,0) NOT NULL,
    vat_tu_id bigint NOT NULL,
    phieu_nhap_id bigint NOT NULL
);


ALTER TABLE public.cuahang_chitietphieunhap OWNER TO postgres;

--
-- TOC entry 264 (class 1259 OID 25852)
-- Name: cuahang_chitietphieunhap_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cuahang_chitietphieunhap ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuahang_chitietphieunhap_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 269 (class 1259 OID 25896)
-- Name: cuahang_chitietphieuxuat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuahang_chitietphieuxuat (
    id bigint NOT NULL,
    so_luong_xuat double precision NOT NULL,
    vat_tu_id bigint NOT NULL,
    phieu_xuat_id bigint NOT NULL
);


ALTER TABLE public.cuahang_chitietphieuxuat OWNER TO postgres;

--
-- TOC entry 268 (class 1259 OID 25895)
-- Name: cuahang_chitietphieuxuat_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cuahang_chitietphieuxuat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuahang_chitietphieuxuat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 17661)
-- Name: cuahang_cuahang; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuahang_cuahang (
    id bigint NOT NULL,
    ten_quan character varying(100) NOT NULL,
    dia_chi character varying(200) NOT NULL,
    vi_tri public.geometry(Point,4326) NOT NULL,
    ban_kinh double precision NOT NULL,
    so_dien_thoai character varying(20)
);


ALTER TABLE public.cuahang_cuahang OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 17660)
-- Name: cuahang_cuahang_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cuahang_cuahang ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuahang_cuahang_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 25687)
-- Name: cuahang_danhgia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuahang_danhgia (
    id bigint NOT NULL,
    diem_so integer NOT NULL,
    binh_luan text,
    ngay_tao timestamp with time zone NOT NULL,
    cua_hang_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.cuahang_danhgia OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 25686)
-- Name: cuahang_danhgia_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cuahang_danhgia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuahang_danhgia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 25787)
-- Name: cuahang_dinhmuc; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuahang_dinhmuc (
    id bigint NOT NULL,
    so_luong_tieu_hao double precision NOT NULL,
    vat_tu_id bigint NOT NULL,
    san_pham_id bigint NOT NULL
);


ALTER TABLE public.cuahang_dinhmuc OWNER TO postgres;

--
-- TOC entry 258 (class 1259 OID 25786)
-- Name: cuahang_dinhmuc_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cuahang_dinhmuc ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuahang_dinhmuc_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 25714)
-- Name: cuahang_donhang; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuahang_donhang (
    id bigint NOT NULL,
    khach_hang character varying(100) NOT NULL,
    tong_tien numeric(12,0) NOT NULL,
    trang_thai character varying(5) NOT NULL,
    ngay_tao timestamp with time zone NOT NULL,
    cua_hang_id bigint NOT NULL,
    da_tru_kho boolean NOT NULL
);


ALTER TABLE public.cuahang_donhang OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 25713)
-- Name: cuahang_donhang_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cuahang_donhang ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuahang_donhang_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 25753)
-- Name: cuahang_kho; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuahang_kho (
    id bigint NOT NULL,
    so_luong_ton double precision NOT NULL,
    ngay_cap_nhat timestamp with time zone NOT NULL,
    cua_hang_id bigint NOT NULL,
    vat_tu_id bigint NOT NULL
);


ALTER TABLE public.cuahang_kho OWNER TO postgres;

--
-- TOC entry 254 (class 1259 OID 25752)
-- Name: cuahang_kho_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cuahang_kho ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuahang_kho_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 25670)
-- Name: cuahang_nhanvien; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuahang_nhanvien (
    id bigint NOT NULL,
    ho_ten character varying(100) NOT NULL,
    chuc_vu character varying(2) NOT NULL,
    ngay_vao_lam date NOT NULL,
    so_dien_thoai character varying(15) NOT NULL,
    cua_hang_id bigint
);


ALTER TABLE public.cuahang_nhanvien OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 25669)
-- Name: cuahang_nhanvien_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cuahang_nhanvien ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuahang_nhanvien_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 263 (class 1259 OID 25840)
-- Name: cuahang_phieunhapkho; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuahang_phieunhapkho (
    id bigint NOT NULL,
    ngay_tao timestamp with time zone NOT NULL,
    nguoi_nhap character varying(100) NOT NULL,
    ghi_chu text,
    da_cong_kho boolean NOT NULL,
    cua_hang_id bigint NOT NULL
);


ALTER TABLE public.cuahang_phieunhapkho OWNER TO postgres;

--
-- TOC entry 262 (class 1259 OID 25839)
-- Name: cuahang_phieunhapkho_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cuahang_phieunhapkho ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuahang_phieunhapkho_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 267 (class 1259 OID 25882)
-- Name: cuahang_phieuxuatkho; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuahang_phieuxuatkho (
    id bigint NOT NULL,
    ngay_tao timestamp with time zone NOT NULL,
    nguoi_xuat character varying(100) NOT NULL,
    ly_do character varying(15) NOT NULL,
    ghi_chu text,
    da_tru_kho boolean NOT NULL,
    cua_hang_id bigint NOT NULL
);


ALTER TABLE public.cuahang_phieuxuatkho OWNER TO postgres;

--
-- TOC entry 266 (class 1259 OID 25881)
-- Name: cuahang_phieuxuatkho_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cuahang_phieuxuatkho ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuahang_phieuxuatkho_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 257 (class 1259 OID 25778)
-- Name: cuahang_sanpham; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuahang_sanpham (
    id bigint NOT NULL,
    ten_mon character varying(100) NOT NULL,
    gia_ban numeric(10,0) NOT NULL
);


ALTER TABLE public.cuahang_sanpham OWNER TO postgres;

--
-- TOC entry 256 (class 1259 OID 25777)
-- Name: cuahang_sanpham_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cuahang_sanpham ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuahang_sanpham_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 253 (class 1259 OID 25744)
-- Name: cuahang_vattu; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuahang_vattu (
    id bigint NOT NULL,
    ten character varying(100) NOT NULL,
    don_vi character varying(20) NOT NULL
);


ALTER TABLE public.cuahang_vattu OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 25743)
-- Name: cuahang_vattu_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cuahang_vattu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuahang_vattu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 17620)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 17619)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 17490)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 17489)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 17478)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17477)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 17674)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 6161 (class 0 OID 17512)
-- Dependencies: 232
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
2	quản lý
\.


--
-- TOC entry 6163 (class 0 OID 17522)
-- Dependencies: 234
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
3	2	1
4	2	9
5	2	25
\.


--
-- TOC entry 6159 (class 0 OID 17502)
-- Dependencies: 230
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add cua hang	7	add_cuahang
26	Can change cua hang	7	change_cuahang
27	Can delete cua hang	7	delete_cuahang
28	Can view cua hang	7	view_cuahang
29	Can add Nhân viên	8	add_nhanvien
30	Can change Nhân viên	8	change_nhanvien
31	Can delete Nhân viên	8	delete_nhanvien
32	Can view Nhân viên	8	view_nhanvien
33	Can add Đánh giá	9	add_danhgia
34	Can change Đánh giá	9	change_danhgia
35	Can delete Đánh giá	9	delete_danhgia
36	Can view Đánh giá	9	view_danhgia
37	Can add Đơn hàng	10	add_donhang
38	Can change Đơn hàng	10	change_donhang
39	Can delete Đơn hàng	10	delete_donhang
40	Can view Đơn hàng	10	view_donhang
41	Can add kho	11	add_kho
42	Can change kho	11	change_kho
43	Can delete kho	11	delete_kho
44	Can view kho	11	view_kho
45	Can add vat tu	12	add_vattu
46	Can change vat tu	12	change_vattu
47	Can delete vat tu	12	delete_vattu
48	Can view vat tu	12	view_vattu
49	Can add Sản phẩm	14	add_sanpham
50	Can change Sản phẩm	14	change_sanpham
51	Can delete Sản phẩm	14	delete_sanpham
52	Can view Sản phẩm	14	view_sanpham
53	Can add Định mức nguyên liệu	13	add_dinhmuc
54	Can change Định mức nguyên liệu	13	change_dinhmuc
55	Can delete Định mức nguyên liệu	13	delete_dinhmuc
56	Can view Định mức nguyên liệu	13	view_dinhmuc
57	Can add Chi tiết món	15	add_chitietdonhang
58	Can change Chi tiết món	15	change_chitietdonhang
59	Can delete Chi tiết món	15	delete_chitietdonhang
60	Can view Chi tiết món	15	view_chitietdonhang
61	Can add Phiếu nhập kho	17	add_phieunhapkho
62	Can change Phiếu nhập kho	17	change_phieunhapkho
63	Can delete Phiếu nhập kho	17	delete_phieunhapkho
64	Can view Phiếu nhập kho	17	view_phieunhapkho
65	Can add Chi tiết nhập	16	add_chitietphieunhap
66	Can change Chi tiết nhập	16	change_chitietphieunhap
67	Can delete Chi tiết nhập	16	delete_chitietphieunhap
68	Can view Chi tiết nhập	16	view_chitietphieunhap
69	Can add Chi tiết xuất	18	add_chitietphieuxuat
70	Can change Chi tiết xuất	18	change_chitietphieuxuat
71	Can delete Chi tiết xuất	18	delete_chitietphieuxuat
72	Can view Chi tiết xuất	18	view_chitietphieuxuat
73	Can add Phiếu xuất kho	19	add_phieuxuatkho
74	Can change Phiếu xuất kho	19	change_phieuxuatkho
75	Can delete Phiếu xuất kho	19	delete_phieuxuatkho
76	Can view Phiếu xuất kho	19	view_phieuxuatkho
\.


--
-- TOC entry 6165 (class 0 OID 17531)
-- Dependencies: 236
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
3	!MB7urGf3hbTEfpQNWRf98KEvRnrE6gjOqC7UGQG8	\N	f	Hoàng				f	t	2026-02-05 11:44:08.305483+07
5	pbkdf2_sha256$1200000$7Z3htf68ImINyU9UX37Q6t$2yQCM0/2/o0xtUFPGt7y6ePceE2kva5a1GMkYXCE16w=	\N	f	minh				f	t	2026-04-01 13:23:28.790656+07
4	pbkdf2_sha256$1200000$nBLEDURK5OP38KvIZH6zjt$DCxJO6cts+eTNpCrnF9Cz95TNJq1XqIe2IINNxJXpnU=	2026-04-01 13:24:25.757202+07	t	hau				t	t	2026-02-06 13:08:04+07
6	pbkdf2_sha256$1200000$G7rYKqEzgt537cbD9edKfT$TfYzlQ56nslk4aDd2qDa8pF6GRheG6tyVEt3xXMARlI=	2026-04-08 13:48:34.844+07	f	ha				f	t	2026-04-08 13:20:25.359551+07
2	pbkdf2_sha256$1200000$ezvnviV2uWUsg9sOn3FEz7$PYhAyK45eHhbJ+UJ8fyBGK2I1iIDkGVSe2OsGTaNKj0=	\N	t	Hiếu				t	t	2026-02-05 11:23:49+07
1	pbkdf2_sha256$1200000$aWmvCCdSnOBugdKktbNhs9$cS/tLm1ehIdwkkTaaVTYxjsZe5uwHpLR//INlALIwJ0=	2026-04-22 14:00:38.970368+07	t	admin				t	t	2026-02-04 11:12:26.961744+07
\.


--
-- TOC entry 6167 (class 0 OID 17550)
-- Dependencies: 238
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
1	2	2
\.


--
-- TOC entry 6169 (class 0 OID 17559)
-- Dependencies: 240
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
1	2	1
2	2	2
3	2	3
4	2	4
5	2	5
6	2	6
7	2	7
8	2	8
9	2	9
10	2	10
11	2	11
12	2	12
13	2	13
14	2	14
15	2	15
16	2	16
17	2	17
18	2	18
19	2	19
20	2	20
21	2	21
22	2	22
23	2	23
24	2	24
25	2	25
26	2	26
27	2	27
28	2	28
29	2	29
30	2	30
31	2	31
32	2	32
33	2	33
34	2	34
35	2	35
36	2	36
37	2	37
38	2	38
39	2	39
40	2	40
\.


--
-- TOC entry 6190 (class 0 OID 25815)
-- Dependencies: 261
-- Data for Name: cuahang_chitietdonhang; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuahang_chitietdonhang (id, so_luong, don_hang_id, san_pham_id) FROM stdin;
1	1	7	2
2	1	7	1
13	1	13	2
14	1	13	1
15	1	14	2
16	1	14	1
17	1	15	2
18	1	15	1
19	1	16	2
20	1	16	1
21	1	17	2
22	1	17	1
23	1	18	1
24	1	18	2
25	1	19	1
26	1	19	2
\.


--
-- TOC entry 6194 (class 0 OID 25853)
-- Dependencies: 265
-- Data for Name: cuahang_chitietphieunhap; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuahang_chitietphieunhap (id, so_luong_nhap, don_gia, vat_tu_id, phieu_nhap_id) FROM stdin;
1	50	250000	8	1
\.


--
-- TOC entry 6198 (class 0 OID 25896)
-- Dependencies: 269
-- Data for Name: cuahang_chitietphieuxuat; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuahang_chitietphieuxuat (id, so_luong_xuat, vat_tu_id, phieu_xuat_id) FROM stdin;
1	1	7	1
\.


--
-- TOC entry 6173 (class 0 OID 17661)
-- Dependencies: 244
-- Data for Name: cuahang_cuahang; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuahang_cuahang (id, ten_quan, dia_chi, vi_tri, ban_kinh, so_dien_thoai) FROM stdin;
5	Hiếu Hoàng Hậu 1	63 3 tháng  2	0101000020E61000002C49B87E6BAB5A40BD7D6EFD5B8C2540	5	\N
4	Hiếu Hoàng Hậu 2	226 Lê Văn Sỹ	0101000020E6100000FEC8867CBDAA5A408F61AABFE4962540	5	\N
3	Hiếu Hoàng Hậu 3	CC1 Trường Sơn	0101000020E610000071ED891A71AA5A40FCFD361B54902540	5	\N
2	Hiếu Hoàng Hậu 4	236b Lê Văn Sỹ	0101000020E6100000C000ADFAADAA5A403FE014C7BF972540	5	\N
1	Hiếu Hoàng Hậu 5	333 Lê Văn Sỹ	0101000020E6100000282D521BA8AA5A40EDF6C0BD4B972540	5	\N
8	Hiếu Hoàng Hậu 6	Trường Trung học cơ sở Nguyễn Minh Hoàng, 185/2, Đường Lý Thường Kiệt, Khu phố 2, Phường Minh Phụng, Thành phố Thủ Đức, Thành phố Hồ Chí Minh, 72415, Việt Nam	0101000020E61000002EAD86C43DAA5A40C4D155BABB862540	5	\N
\.


--
-- TOC entry 6178 (class 0 OID 25687)
-- Dependencies: 249
-- Data for Name: cuahang_danhgia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuahang_danhgia (id, diem_so, binh_luan, ngay_tao, cua_hang_id, user_id) FROM stdin;
2	5	\N	2026-04-08 12:28:09.106399+07	3	1
4	4	\N	2026-04-08 12:28:17.307146+07	2	1
5	4	\N	2026-04-08 12:28:21.717474+07	1	1
1	5	\N	2026-04-08 12:28:03.571267+07	5	1
3	1		2026-04-08 12:28:13.238888+07	4	1
6	5	tot	2026-04-08 13:29:56.600509+07	4	6
\.


--
-- TOC entry 6188 (class 0 OID 25787)
-- Dependencies: 259
-- Data for Name: cuahang_dinhmuc; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuahang_dinhmuc (id, so_luong_tieu_hao, vat_tu_id, san_pham_id) FROM stdin;
1	1	6	1
2	1	7	1
3	1	4	2
4	0.2	5	2
5	1	4	1
6	1	8	3
\.


--
-- TOC entry 6180 (class 0 OID 25714)
-- Dependencies: 251
-- Data for Name: cuahang_donhang; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuahang_donhang (id, khach_hang, tong_tien, trang_thai, ngay_tao, cua_hang_id, da_tru_kho) FROM stdin;
1	Khách vãng lai	50000	HT	2026-04-08 14:05:18.607622+07	5	f
2	Khách vãng lai	100000	HT	2026-04-08 14:12:12.230061+07	4	f
3	Khách vãng lai	20000	HT	2026-04-08 14:18:58.154356+07	3	f
4	Khách vãng lai	200000	HT	2026-04-08 14:19:24.152347+07	2	f
5	Khách vãng lai	500000	HT	2026-04-08 14:19:33.199968+07	1	f
14	Khách vãng lai	45000	HT	2026-04-08 17:30:15.361824+07	5	t
15	Khách vãng lai	45000	HT	2026-04-08 17:30:42.62991+07	5	t
16	Khách vãng lai	45000	HT	2026-04-08 17:41:56.142349+07	5	t
17	Khách vãng lai	45000	DH	2026-04-15 07:31:53.679711+07	5	t
18	Khách vãng lai	45000	HT	2026-04-21 15:48:40.150657+07	5	t
7	Khách vãng lai	45000	HT	2026-04-08 16:50:54.049306+07	5	t
19	Khách vãng lai	45000	HT	2026-04-22 13:10:29.158527+07	5	t
13	Khách vãng lai	45000	HT	2026-04-08 17:23:32.261499+07	5	f
\.


--
-- TOC entry 6184 (class 0 OID 25753)
-- Dependencies: 255
-- Data for Name: cuahang_kho; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuahang_kho (id, so_luong_ton, ngay_cap_nhat, cua_hang_id, vat_tu_id) FROM stdin;
8	88	2026-04-08 17:06:46.105533+07	5	6
6	76	2026-04-08 17:07:01.858449+07	5	4
7	97.59999999999997	2026-04-08 17:06:53.648631+07	5	5
14	1	2026-05-04 14:08:21.713968+07	3	8
12	50	2026-05-04 14:40:36.298889+07	4	8
15	50	2026-05-04 14:48:04.030351+07	8	8
11	47	2026-04-21 15:47:50.744535+07	5	7
\.


--
-- TOC entry 6176 (class 0 OID 25670)
-- Dependencies: 247
-- Data for Name: cuahang_nhanvien; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuahang_nhanvien (id, ho_ten, chuc_vu, ngay_vao_lam, so_dien_thoai, cua_hang_id) FROM stdin;
1	Ngô Duy Hiếu	QL	2026-02-06	0123456789	5
2	Như Sỹ  Hoàng	BV	2026-02-06	123456778	5
3	Nguyên	NV	2026-02-06	123	4
4	minh	NV	2026-02-06	124	3
5	khoa	NV	2026-02-06	456	1
6	đạt	NV	2026-04-22	3456	4
\.


--
-- TOC entry 6192 (class 0 OID 25840)
-- Dependencies: 263
-- Data for Name: cuahang_phieunhapkho; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuahang_phieunhapkho (id, ngay_tao, nguoi_nhap, ghi_chu, da_cong_kho, cua_hang_id) FROM stdin;
1	2026-05-04 14:48:04.015921+07	hau	pepsi	t	8
\.


--
-- TOC entry 6196 (class 0 OID 25882)
-- Dependencies: 267
-- Data for Name: cuahang_phieuxuatkho; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuahang_phieuxuatkho (id, ngay_tao, nguoi_xuat, ly_do, ghi_chu, da_tru_kho, cua_hang_id) FROM stdin;
1	2026-05-04 14:54:38.615071+07	hau	HU_HONG	chuot  an	t	5
\.


--
-- TOC entry 6186 (class 0 OID 25778)
-- Dependencies: 257
-- Data for Name: cuahang_sanpham; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuahang_sanpham (id, ten_mon, gia_ban) FROM stdin;
2	Cafe	20000
1	Trà dâu	25000
3	khô gà	50000
\.


--
-- TOC entry 6182 (class 0 OID 25744)
-- Dependencies: 253
-- Data for Name: cuahang_vattu; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuahang_vattu (id, ten, don_vi) FROM stdin;
4	Cốc	cái
5	Cafe	kg
6	trà lài	bịch
7	mứt dâu	bịch
8	khô gà	hộp
\.


--
-- TOC entry 6171 (class 0 OID 17620)
-- Dependencies: 242
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-02-05 09:50:37.662352+07	1	Hiếu Hoàng Hậu	1	[{"added": {}}]	7	1
2	2026-02-05 10:06:02.659335+07	2	Hiếu Hoàng Hậu	1	[{"added": {}}]	7	1
3	2026-02-05 10:08:48.275787+07	3	Hiếu Hoàng Hậu	1	[{"added": {}}]	7	1
4	2026-02-05 11:22:30.94818+07	1	Hiếu	1	[{"added": {}}]	2	1
5	2026-02-05 11:23:21.232151+07	1	Hiếu	3		2	1
6	2026-02-05 11:23:49.864754+07	2	Hiếu	1	[{"added": {}}]	4	1
7	2026-02-05 11:24:15.663213+07	2	Hiếu	2	[]	4	1
8	2026-02-05 11:41:59.565991+07	4	Hiếu Hoàng Hậu	1	[{"added": {}}]	7	1
9	2026-02-05 11:44:08.316177+07	3	Hoàng	1	[{"added": {}}]	4	1
10	2026-02-05 12:15:14.244365+07	5	Hiếu Hoàng Hậu	1	[{"added": {}}]	7	1
11	2026-02-06 11:59:45.484829+07	2	quản lý	1	[{"added": {}}]	2	1
12	2026-02-06 12:02:26.375264+07	2	Hiếu	2	[{"changed": {"fields": ["Groups"]}}]	4	1
13	2026-02-06 13:08:06.148541+07	4	hau	1	[{"added": {}}]	4	1
14	2026-02-06 13:08:39.549048+07	4	hau	2	[{"changed": {"fields": ["Staff status", "Superuser status"]}}]	4	1
15	2026-02-06 13:12:13.461013+07	5	Hiếu Hoàng Hậu 1	2	[{"changed": {"fields": ["T\\u00ean Qu\\u00e1n"]}}]	7	1
16	2026-02-06 13:12:17.604148+07	4	Hiếu Hoàng Hậu 2	2	[{"changed": {"fields": ["T\\u00ean Qu\\u00e1n"]}}]	7	1
17	2026-02-06 13:12:21.040077+07	3	Hiếu Hoàng Hậu 3	2	[{"changed": {"fields": ["T\\u00ean Qu\\u00e1n"]}}]	7	1
18	2026-02-06 13:12:24.389379+07	2	Hiếu Hoàng Hậu 4	2	[{"changed": {"fields": ["T\\u00ean Qu\\u00e1n"]}}]	7	1
19	2026-02-06 13:12:28.726089+07	1	Hiếu Hoàng Hậu 5	2	[{"changed": {"fields": ["T\\u00ean Qu\\u00e1n"]}}]	7	1
20	2026-02-06 13:12:49.044053+07	1	Ngô Duy Hiếu (Quản lý cửa hàng)	1	[{"added": {}}]	8	1
21	2026-02-06 13:13:18.028711+07	2	Như Sỹ  Hoàng (Bảo vệ)	1	[{"added": {}}]	8	1
22	2026-02-06 13:13:36.742109+07	3	Nguyên (Nhân viên bán hàng)	1	[{"added": {}}]	8	1
23	2026-02-06 13:13:49.013253+07	4	minh (Nhân viên bán hàng)	1	[{"added": {}}]	8	1
24	2026-02-06 13:14:01.006727+07	5	khoa (Nhân viên bán hàng)	1	[{"added": {}}]	8	1
25	2026-04-01 13:19:56.764523+07	2	Hiếu	2	[{"changed": {"fields": ["password"]}}]	4	1
26	2026-04-01 13:20:03.742429+07	2	Hiếu	2	[]	4	1
27	2026-04-01 13:20:08.597858+07	2	Hiếu	2	[]	4	1
28	2026-04-01 13:23:30.99005+07	5	minh	1	[{"added": {}}]	4	1
29	2026-04-01 15:07:51.617809+07	2	Hiếu	2	[{"changed": {"fields": ["Staff status"]}}]	4	1
30	2026-04-01 15:08:08.297136+07	2	Hiếu	2	[{"changed": {"fields": ["Staff status"]}}]	4	1
31	2026-04-08 13:20:26.661899+07	6	ha	1	[{"added": {}}]	4	1
32	2026-04-08 14:05:18.615252+07	1	Đơn #1 - Hiếu Hoàng Hậu 1 - 50000đ	1	[{"added": {}}]	10	1
33	2026-04-08 14:12:12.232443+07	2	Đơn #2 - Hiếu Hoàng Hậu 2 - 100000đ	1	[{"added": {}}]	10	1
34	2026-04-08 14:18:58.157571+07	3	Đơn #3 - Hiếu Hoàng Hậu 3 - 20000đ	1	[{"added": {}}]	10	1
35	2026-04-08 14:19:24.154633+07	4	Đơn #4 - Hiếu Hoàng Hậu 4 - 200000đ	1	[{"added": {}}]	10	1
36	2026-04-08 14:19:33.20156+07	5	Đơn #5 - Hiếu Hoàng Hậu 5 - 500000đ	1	[{"added": {}}]	10	1
37	2026-04-08 15:00:45.346073+07	2	Hiếu	2	[{"changed": {"fields": ["Staff status", "Superuser status", "User permissions"]}}]	4	1
38	2026-04-08 15:13:24.619493+07	6	Đơn #6 - Hiếu Hoàng Hậu 1 - 50000đ	1	[{"added": {}}]	10	1
39	2026-04-08 15:55:07.683134+07	1	giấy	1	[{"added": {}}]	12	1
40	2026-04-08 15:55:30.656631+07	1	Hiếu Hoàng Hậu 1 - giấy	1	[{"added": {}}]	11	1
41	2026-04-08 15:56:39.952458+07	1	Hiếu Hoàng Hậu 1 - giấy	3		11	1
42	2026-04-08 15:56:52.1671+07	1	giấy	3		12	1
43	2026-04-08 15:58:19.997179+07	2	giấy	1	[{"added": {}}]	12	1
44	2026-04-08 15:58:31.671314+07	2	Hiếu Hoàng Hậu 1 - giấy	1	[{"added": {}}]	11	1
45	2026-04-08 16:13:24.581523+07	6	Đơn #6 - Hiếu Hoàng Hậu 1 - 50000đ	2	[{"changed": {"fields": ["Trang thai"]}}]	10	1
46	2026-04-08 16:13:56.572816+07	3	cốc	1	[{"added": {}}]	12	1
47	2026-04-08 16:14:13.75746+07	6	Đơn #6 - Hiếu Hoàng Hậu 1 - 50000đ	2	[{"changed": {"fields": ["Trang thai"]}}]	10	1
48	2026-04-08 16:14:27.877764+07	3	Hiếu Hoàng Hậu 1 - cốc	1	[{"added": {}}]	11	1
49	2026-04-08 16:14:38.51795+07	6	Đơn #6 - Hiếu Hoàng Hậu 1 - 50000đ	2	[{"changed": {"fields": ["Trang thai"]}}]	10	1
50	2026-04-08 16:18:59.38793+07	3	Hiếu Hoàng Hậu 1 - cốc	3		11	1
51	2026-04-08 16:18:59.387974+07	2	Hiếu Hoàng Hậu 1 - giấy	3		11	1
52	2026-04-08 16:19:06.798045+07	3	cốc	3		12	1
53	2026-04-08 16:19:06.798155+07	2	giấy	3		12	1
54	2026-04-08 16:19:21.515817+07	4	Cốc	1	[{"added": {}}]	12	1
55	2026-04-08 16:19:34.733948+07	5	Cafe	1	[{"added": {}}]	12	1
56	2026-04-08 16:19:51.407228+07	6	Đơn #6 - Hiếu Hoàng Hậu 1 - 50000đ	2	[{"changed": {"fields": ["Trang thai"]}}]	10	1
57	2026-04-08 16:20:01.834581+07	4	Hiếu Hoàng Hậu 1 - Cốc	1	[{"added": {}}]	11	1
58	2026-04-08 16:20:11.651624+07	5	Hiếu Hoàng Hậu 1 - Cafe	1	[{"added": {}}]	11	1
59	2026-04-08 16:20:22.164204+07	6	Đơn #6 - Hiếu Hoàng Hậu 1 - 50000đ	2	[{"changed": {"fields": ["Trang thai"]}}]	10	1
60	2026-04-08 16:36:06.272242+07	6	trà lài	1	[{"added": {}}]	12	1
61	2026-04-08 16:36:15.999951+07	7	mứt dâu	1	[{"added": {}}]	12	1
62	2026-04-08 16:36:45.819925+07	1	trà dâu	1	[{"added": {}}, {"added": {"name": "\\u0110\\u1ecbnh m\\u1ee9c nguy\\u00ean li\\u1ec7u", "object": "DinhMuc object (1)"}}, {"added": {"name": "\\u0110\\u1ecbnh m\\u1ee9c nguy\\u00ean li\\u1ec7u", "object": "DinhMuc object (2)"}}]	14	1
63	2026-04-08 16:37:16.86693+07	2	Cafe	1	[{"added": {}}, {"added": {"name": "\\u0110\\u1ecbnh m\\u1ee9c nguy\\u00ean li\\u1ec7u", "object": "DinhMuc object (3)"}}, {"added": {"name": "\\u0110\\u1ecbnh m\\u1ee9c nguy\\u00ean li\\u1ec7u", "object": "DinhMuc object (4)"}}]	14	1
64	2026-04-08 16:37:19.660216+07	2	Cafe	2	[]	14	1
65	2026-04-08 16:37:36.779578+07	1	Trà dâu	2	[{"changed": {"fields": ["T\\u00ean m\\u00f3n"]}}, {"added": {"name": "\\u0110\\u1ecbnh m\\u1ee9c nguy\\u00ean li\\u1ec7u", "object": "DinhMuc object (5)"}}]	14	1
66	2026-04-08 16:37:49.77267+07	5	Hiếu Hoàng Hậu 1 - Cafe	3		11	1
67	2026-04-08 16:37:49.772729+07	4	Hiếu Hoàng Hậu 1 - Cốc	3		11	1
68	2026-04-08 16:38:17.842367+07	6	Hiếu Hoàng Hậu 1 - Cốc	1	[{"added": {}}]	11	1
69	2026-04-08 16:38:25.109615+07	7	Hiếu Hoàng Hậu 1 - Cafe	1	[{"added": {}}]	11	1
70	2026-04-08 16:38:31.601926+07	8	Hiếu Hoàng Hậu 1 - trà lài	1	[{"added": {}}]	11	1
71	2026-04-08 16:38:39.092182+07	9	Hiếu Hoàng Hậu 1 - mứt dâu	1	[{"added": {}}]	11	1
72	2026-04-08 16:50:54.085188+07	7	DonHang object (7)	1	[{"added": {}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (1)"}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (2)"}}]	10	1
73	2026-04-08 16:51:04.507225+07	7	DonHang object (7)	2	[{"changed": {"fields": ["Trang thai"]}}]	10	1
74	2026-04-08 16:51:28.358516+07	7	DonHang object (7)	2	[{"changed": {"fields": ["Trang thai"]}}]	10	1
75	2026-04-08 16:51:43.370048+07	7	DonHang object (7)	2	[]	10	1
76	2026-04-08 16:52:31.846304+07	6	DonHang object (6)	3		10	1
77	2026-04-08 16:52:44.498381+07	7	DonHang object (7)	2	[]	10	1
78	2026-04-08 16:55:57.17515+07	7	DonHang object (7)	2	[]	10	1
79	2026-04-08 16:58:45.155155+07	7	DonHang object (7)	2	[]	10	1
80	2026-04-08 17:06:39.833338+07	9	Hiếu Hoàng Hậu 1 - mứt dâu	2	[{"changed": {"fields": ["So luong ton"]}}]	11	1
81	2026-04-08 17:06:46.108425+07	8	Hiếu Hoàng Hậu 1 - trà lài	2	[{"changed": {"fields": ["So luong ton"]}}]	11	1
82	2026-04-08 17:06:53.649859+07	7	Hiếu Hoàng Hậu 1 - Cafe	2	[{"changed": {"fields": ["So luong ton"]}}]	11	1
83	2026-04-08 17:07:01.860607+07	6	Hiếu Hoàng Hậu 1 - Cốc	2	[{"changed": {"fields": ["So luong ton"]}}]	11	1
84	2026-04-08 17:08:33.746756+07	7	DonHang object (7)	2	[]	10	1
85	2026-04-08 17:11:30.812592+07	7	DonHang object (7)	2	[]	10	1
86	2026-04-08 17:11:43.391136+07	7	DonHang object (7)	2	[{"changed": {"fields": ["Trang thai"]}}]	10	1
87	2026-04-08 17:11:48.076789+07	7	DonHang object (7)	2	[{"changed": {"fields": ["Trang thai"]}}]	10	1
88	2026-04-08 17:14:17.537727+07	8	DonHang object (8)	1	[{"added": {}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (3)"}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (4)"}}]	10	1
89	2026-04-08 17:14:44.214834+07	8	DonHang object (8)	3		10	1
90	2026-04-08 17:14:55.82151+07	9	DonHang object (9)	1	[{"added": {}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (5)"}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (6)"}}]	10	1
91	2026-04-08 17:15:04.365326+07	9	DonHang object (9)	2	[{"changed": {"fields": ["Trang thai"]}}]	10	1
92	2026-04-08 17:15:22.869623+07	9	DonHang object (9)	2	[]	10	1
93	2026-04-08 17:15:31.051793+07	9	DonHang object (9)	3		10	1
94	2026-04-08 17:15:41.60171+07	10	DonHang object (10)	1	[{"added": {}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (7)"}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (8)"}}]	10	1
95	2026-04-08 17:22:02.69178+07	10	Đơn #10 - Hiếu Hoàng Hậu 1	2	[]	10	1
96	2026-04-08 17:22:09.305067+07	10	Đơn #10 - Hiếu Hoàng Hậu 1	2	[]	10	1
97	2026-04-08 17:22:28.586229+07	11	Đơn #11 - Hiếu Hoàng Hậu 1	1	[{"added": {}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (9)"}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (10)"}}]	10	1
98	2026-04-08 17:22:42.977002+07	11	Đơn #11 - Hiếu Hoàng Hậu 1	3		10	1
99	2026-04-08 17:22:42.977052+07	10	Đơn #10 - Hiếu Hoàng Hậu 1	3		10	1
100	2026-04-08 17:22:57.276244+07	12	Đơn #12 - Hiếu Hoàng Hậu 1	1	[{"added": {}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (11)"}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (12)"}}]	10	1
101	2026-04-08 17:23:17.604797+07	12	Đơn #12 - Hiếu Hoàng Hậu 1	3		10	1
102	2026-04-08 17:23:32.283633+07	13	Đơn #13 - Hiếu Hoàng Hậu 1	1	[{"added": {}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (13)"}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (14)"}}]	10	1
103	2026-04-08 17:23:41.967832+07	13	Đơn #13 - Hiếu Hoàng Hậu 1	2	[{"changed": {"fields": ["Trang thai"]}}]	10	1
104	2026-04-08 17:30:15.419836+07	14	Đơn #14 - Hiếu Hoàng Hậu 1	1	[{"added": {}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (15)"}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (16)"}}]	10	1
105	2026-04-08 17:30:27.391928+07	14	Đơn #14 - Hiếu Hoàng Hậu 1	2	[]	10	1
106	2026-04-08 17:30:42.640593+07	15	Đơn #15 - Hiếu Hoàng Hậu 1	1	[{"added": {}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (17)"}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (18)"}}]	10	1
107	2026-04-08 17:30:48.961099+07	15	Đơn #15 - Hiếu Hoàng Hậu 1	2	[{"changed": {"fields": ["Trang thai"]}}]	10	1
108	2026-04-08 17:41:56.154086+07	16	Đơn #16 - Hiếu Hoàng Hậu 1	1	[{"added": {}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (19)"}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (20)"}}]	10	1
109	2026-04-08 17:42:51.989387+07	16	Đơn #16 - Hiếu Hoàng Hậu 1	2	[{"changed": {"fields": ["Trang thai"]}}]	10	1
110	2026-04-15 07:31:53.710445+07	17	Đơn #17 - Hiếu Hoàng Hậu 1	1	[{"added": {}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (21)"}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (22)"}}]	10	1
111	2026-04-15 07:33:45.60945+07	17	Đơn #17 - Hiếu Hoàng Hậu 1	2	[{"changed": {"fields": ["Trang thai"]}}]	10	1
112	2026-04-21 15:34:36.292469+07	17	Đơn #17 - Hiếu Hoàng Hậu 1	2	[{"changed": {"fields": ["Trang thai"]}}]	10	1
113	2026-04-21 15:36:06.74277+07	9	Hiếu Hoàng Hậu 1 - mứt dâu	3		11	1
114	2026-04-21 15:36:15.33782+07	10	Hiếu Hoàng Hậu 1 - mứt dâu	1	[{"added": {}}]	11	1
115	2026-04-21 15:47:38.094479+07	10	Hiếu Hoàng Hậu 1 - mứt dâu	3		11	1
116	2026-04-21 15:47:50.746627+07	11	Hiếu Hoàng Hậu 1 - mứt dâu	1	[{"added": {}}]	11	1
117	2026-04-21 15:48:40.24522+07	18	Đơn #18 - Hiếu Hoàng Hậu 1	1	[{"added": {}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (23)"}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (24)"}}]	10	1
118	2026-04-22 13:01:17.923481+07	6	đạt (Nhân viên bán hàng)	1	[{"added": {}}]	8	1
119	2026-04-22 13:10:29.188088+07	19	Đơn #19 - Hiếu Hoàng Hậu 1	1	[{"added": {}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (25)"}}]	10	1
120	2026-04-22 13:11:14.919114+07	19	Đơn #19 - Hiếu Hoàng Hậu 1	2	[{"changed": {"fields": ["Trang thai"]}}, {"added": {"name": "Chi ti\\u1ebft m\\u00f3n", "object": "ChiTietDonHang object (26)"}}]	10	1
121	2026-04-22 13:12:19.940105+07	8	khô gà	1	[{"added": {}}]	12	1
122	2026-04-22 13:13:05.736334+07	3	khô gà	1	[{"added": {}}, {"added": {"name": "\\u0110\\u1ecbnh m\\u1ee9c nguy\\u00ean li\\u1ec7u", "object": "DinhMuc object (6)"}}]	14	1
123	2026-04-22 13:13:28.795539+07	12	Hiếu Hoàng Hậu 2 - khô gà	1	[{"added": {}}]	11	1
124	2026-04-22 13:14:26.168258+07	13	Hiếu Hoàng Hậu 3 - khô gà	1	[{"added": {}}]	11	1
125	2026-05-04 13:22:55.394988+07	6	Hiếu Hoàng Hậu 6	1	[{"added": {}}]	7	1
126	2026-05-04 13:23:02.496852+07	6	Hiếu Hoàng Hậu 6	3		7	1
127	2026-05-04 13:25:22.219297+07	7	Hiếu Hoàng Hậu 6	1	[{"added": {}}]	7	1
128	2026-05-04 13:25:37.207101+07	7	Hiếu Hoàng Hậu 6	3		7	1
129	2026-05-04 14:04:14.499697+07	8	Hiếu Hoàng Hậu 6	1	[{"added": {}}]	7	1
130	2026-05-04 14:08:03.07045+07	13	Hiếu Hoàng Hậu 3 - khô gà	3		11	1
131	2026-05-04 14:08:13.325902+07	14	Hiếu Hoàng Hậu 3 - khô gà	1	[{"added": {}}]	11	1
132	2026-05-04 14:08:21.716066+07	14	Hiếu Hoàng Hậu 3 - khô gà	2	[{"changed": {"fields": ["S\\u1ed1 l\\u01b0\\u1ee3ng t\\u1ed3n"]}}]	11	1
133	2026-05-04 14:40:19.702812+07	12	Hiếu Hoàng Hậu 2 - khô gà	2	[{"changed": {"fields": ["S\\u1ed1 l\\u01b0\\u1ee3ng t\\u1ed3n"]}}]	11	1
134	2026-05-04 14:40:36.300854+07	12	Hiếu Hoàng Hậu 2 - khô gà	2	[{"changed": {"fields": ["S\\u1ed1 l\\u01b0\\u1ee3ng t\\u1ed3n"]}}]	11	1
135	2026-05-04 14:48:04.036917+07	1	Phiếu #1 - Hiếu Hoàng Hậu 6	1	[{"added": {}}, {"added": {"name": "Chi ti\\u1ebft nh\\u1eadp", "object": "ChiTietPhieuNhap object (1)"}}]	17	1
136	2026-05-04 14:54:38.626408+07	1	Phiếu Xuất #1 - Hiếu Hoàng Hậu 1	1	[{"added": {}}, {"added": {"name": "Chi ti\\u1ebft xu\\u1ea5t", "object": "ChiTietPhieuXuat object (1)"}}]	19	1
\.


--
-- TOC entry 6157 (class 0 OID 17490)
-- Dependencies: 228
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	cuahang	cuahang
8	cuahang	nhanvien
9	cuahang	danhgia
10	cuahang	donhang
11	cuahang	kho
12	cuahang	vattu
13	cuahang	dinhmuc
14	cuahang	sanpham
15	cuahang	chitietdonhang
16	cuahang	chitietphieunhap
17	cuahang	phieunhapkho
18	cuahang	chitietphieuxuat
19	cuahang	phieuxuatkho
\.


--
-- TOC entry 6155 (class 0 OID 17478)
-- Dependencies: 226
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-02-04 10:56:05.306024+07
2	auth	0001_initial	2026-02-04 10:56:05.394211+07
3	admin	0001_initial	2026-02-04 10:56:05.415836+07
4	admin	0002_logentry_remove_auto_add	2026-02-04 10:56:05.42574+07
5	admin	0003_logentry_add_action_flag_choices	2026-02-04 10:56:05.432357+07
6	contenttypes	0002_remove_content_type_name	2026-02-04 10:56:05.447198+07
7	auth	0002_alter_permission_name_max_length	2026-02-04 10:56:05.453161+07
8	auth	0003_alter_user_email_max_length	2026-02-04 10:56:05.458401+07
9	auth	0004_alter_user_username_opts	2026-02-04 10:56:05.463117+07
10	auth	0005_alter_user_last_login_null	2026-02-04 10:56:05.468975+07
11	auth	0006_require_contenttypes_0002	2026-02-04 10:56:05.471287+07
12	auth	0007_alter_validators_add_error_messages	2026-02-04 10:56:05.477356+07
13	auth	0008_alter_user_username_max_length	2026-02-04 10:56:05.488885+07
14	auth	0009_alter_user_last_name_max_length	2026-02-04 10:56:05.499961+07
15	auth	0010_alter_group_name_max_length	2026-02-04 10:56:05.506434+07
16	auth	0011_update_proxy_permissions	2026-02-04 10:56:05.514294+07
17	auth	0012_alter_user_first_name_max_length	2026-02-04 10:56:05.51981+07
18	cuahang	0001_initial	2026-02-04 10:56:05.548012+07
19	sessions	0001_initial	2026-02-04 10:56:05.564844+07
20	cuahang	0002_alter_cuahang_options_cuahang_so_dien_thoai_nhanvien	2026-02-06 13:06:09.101924+07
21	cuahang	0003_danhgia	2026-04-08 10:18:48.58362+07
22	cuahang	0004_donhang	2026-04-08 13:56:51.777144+07
23	cuahang	0005_alter_donhang_khach_hang_alter_donhang_tong_tien_and_more	2026-04-08 15:12:49.200965+07
24	cuahang	0006_vattu_kho	2026-04-08 15:41:32.236286+07
25	cuahang	0007_sanpham_alter_kho_options_alter_vattu_options_and_more	2026-04-08 16:34:51.17396+07
26	cuahang	0008_remove_donhang_san_pham_alter_donhang_khach_hang_and_more	2026-04-08 16:50:17.4309+07
27	cuahang	0009_donhang_da_tru_kho	2026-04-08 17:08:20.049902+07
28	cuahang	0010_alter_chitietdonhang_options	2026-05-04 13:22:34.030531+07
29	cuahang	0011_alter_dinhmuc_so_luong_tieu_hao_and_more	2026-05-04 14:46:06.191637+07
30	cuahang	0012_phieuxuatkho_chitietphieuxuat	2026-05-04 14:53:05.140704+07
\.


--
-- TOC entry 6174 (class 0 OID 17674)
-- Dependencies: 245
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
7dbo22v4jl4o7h6qa2nfo1laydj0kiyi	.eJxVjLsOwjAMAP_FM4r6cog7svcbothOaAElUtNOiH9HlTrAene6N_iwb7Pfa1z9ojBCC5dfxkGeMR9CHyHfi5GSt3VhcyTmtNVMRePrdrZ_gznUGUboWPoeCVWxwdAnx20TcbiSkHVIzuoQrFOLiWxy2AwSpbNM4pIQM8LnC9DkN84:1vnpsf:n1AGgzFfNSSlOGykatagaMSSFhb1dUL5pjpqevmMqJM	2026-02-19 10:18:09.247239+07
18ghgdx5e6y7vvjoafih1cay8ng52nwu	.eJxVjLsOwjAMAP_FM4r6cog7svcbothOaAElUtNOiH9HlTrAene6N_iwb7Pfa1z9ojBCC5dfxkGeMR9CHyHfi5GSt3VhcyTmtNVMRePrdrZ_gznUGUboWPoeCVWxwdAnx20TcbiSkHVIzuoQrFOLiWxy2AwSpbNM4pIQM8LnC9DkN84:1vyO9w:p8mbWPZqPMU_NoK5CkCxnjjcVAYlRxsCj5PlN5agt5A	2026-03-20 12:55:36.037775+07
apqkjgkvlj62f6idhle4cedn3yj1wy5o	.eJxVjLsOwjAMAP_FM4r6cog7svcbothOaAElUtNOiH9HlTrAene6N_iwb7Pfa1z9ojBCC5dfxkGeMR9CHyHfi5GSt3VhcyTmtNVMRePrdrZ_gznUGUboWPoeCVWxwdAnx20TcbiSkHVIzuoQrFOLiWxy2AwSpbNM4pIQM8LnC9DkN84:1wAMhu:SQirc_6wIQPTqBkQrgcAYOlM5hQ-3oms7iDU638DgF8	2026-04-22 13:48:10.222038+07
le1o2osjrxus4v4g7fjuakjgcrpjjvfq	.eJxVjLsOwjAMAP_FM4po09hJR_Z-Q-XYKSmgROpjQvw7qtQB1rvTvWHkfcvjvqZlnBV6QLj8ssjyTOUQ-uByr0Zq2ZY5miMxp13NUDW9bmf7N8i8ZuihJdtRJHEdBr12k0NkG0JIDgO1JExKFCOiF0Ql55P3OpEEimwbaeDzBcCdN1Q:1wAMiI:1jBJj05OY7tLY3-fcDACzxG4AktbzPYrlPcUupd-DrM	2026-04-22 13:48:34.845995+07
xq1fwq3de8g71f3z71byzwxbs9h0arew	.eJxVjLsOwjAMAP_FM4r6cog7svcbothOaAElUtNOiH9HlTrAene6N_iwb7Pfa1z9ojBCC5dfxkGeMR9CHyHfi5GSt3VhcyTmtNVMRePrdrZ_gznUGUboWPoeCVWxwdAnx20TcbiSkHVIzuoQrFOLiWxy2AwSpbNM4pIQM8LnC9DkN84:1wFRZe:BnI3_raK8yUuc8fWxZE-x21NFvKOqN9f-TVema2ACGQ	2026-05-06 14:00:38.972268+07
\.


--
-- TOC entry 5877 (class 0 OID 16708)
-- Dependencies: 221
-- Data for Name: spatial_ref_sys; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.spatial_ref_sys (srid, auth_name, auth_srid, srtext, proj4text) FROM stdin;
\.


--
-- TOC entry 6205 (class 0 OID 0)
-- Dependencies: 231
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 2, true);


--
-- TOC entry 6206 (class 0 OID 0)
-- Dependencies: 233
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 5, true);


--
-- TOC entry 6207 (class 0 OID 0)
-- Dependencies: 229
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 76, true);


--
-- TOC entry 6208 (class 0 OID 0)
-- Dependencies: 237
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, true);


--
-- TOC entry 6209 (class 0 OID 0)
-- Dependencies: 235
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 6, true);


--
-- TOC entry 6210 (class 0 OID 0)
-- Dependencies: 239
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 40, true);


--
-- TOC entry 6211 (class 0 OID 0)
-- Dependencies: 260
-- Name: cuahang_chitietdonhang_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuahang_chitietdonhang_id_seq', 26, true);


--
-- TOC entry 6212 (class 0 OID 0)
-- Dependencies: 264
-- Name: cuahang_chitietphieunhap_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuahang_chitietphieunhap_id_seq', 1, true);


--
-- TOC entry 6213 (class 0 OID 0)
-- Dependencies: 268
-- Name: cuahang_chitietphieuxuat_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuahang_chitietphieuxuat_id_seq', 1, true);


--
-- TOC entry 6214 (class 0 OID 0)
-- Dependencies: 243
-- Name: cuahang_cuahang_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuahang_cuahang_id_seq', 8, true);


--
-- TOC entry 6215 (class 0 OID 0)
-- Dependencies: 248
-- Name: cuahang_danhgia_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuahang_danhgia_id_seq', 6, true);


--
-- TOC entry 6216 (class 0 OID 0)
-- Dependencies: 258
-- Name: cuahang_dinhmuc_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuahang_dinhmuc_id_seq', 6, true);


--
-- TOC entry 6217 (class 0 OID 0)
-- Dependencies: 250
-- Name: cuahang_donhang_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuahang_donhang_id_seq', 19, true);


--
-- TOC entry 6218 (class 0 OID 0)
-- Dependencies: 254
-- Name: cuahang_kho_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuahang_kho_id_seq', 15, true);


--
-- TOC entry 6219 (class 0 OID 0)
-- Dependencies: 246
-- Name: cuahang_nhanvien_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuahang_nhanvien_id_seq', 6, true);


--
-- TOC entry 6220 (class 0 OID 0)
-- Dependencies: 262
-- Name: cuahang_phieunhapkho_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuahang_phieunhapkho_id_seq', 1, true);


--
-- TOC entry 6221 (class 0 OID 0)
-- Dependencies: 266
-- Name: cuahang_phieuxuatkho_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuahang_phieuxuatkho_id_seq', 1, true);


--
-- TOC entry 6222 (class 0 OID 0)
-- Dependencies: 256
-- Name: cuahang_sanpham_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuahang_sanpham_id_seq', 3, true);


--
-- TOC entry 6223 (class 0 OID 0)
-- Dependencies: 252
-- Name: cuahang_vattu_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuahang_vattu_id_seq', 8, true);


--
-- TOC entry 6224 (class 0 OID 0)
-- Dependencies: 241
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 136, true);


--
-- TOC entry 6225 (class 0 OID 0)
-- Dependencies: 227
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 19, true);


--
-- TOC entry 6226 (class 0 OID 0)
-- Dependencies: 225
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 30, true);


--
-- TOC entry 5896 (class 2606 OID 17656)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 5901 (class 2606 OID 17577)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 5904 (class 2606 OID 17529)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 5898 (class 2606 OID 17518)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 5891 (class 2606 OID 17568)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 5893 (class 2606 OID 17510)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 5912 (class 2606 OID 17557)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 5915 (class 2606 OID 17592)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 5906 (class 2606 OID 17546)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 5918 (class 2606 OID 17566)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 5921 (class 2606 OID 17606)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 5909 (class 2606 OID 17649)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 5961 (class 2606 OID 25824)
-- Name: cuahang_chitietdonhang cuahang_chitietdonhang_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_chitietdonhang
    ADD CONSTRAINT cuahang_chitietdonhang_pkey PRIMARY KEY (id);


--
-- TOC entry 5968 (class 2606 OID 25862)
-- Name: cuahang_chitietphieunhap cuahang_chitietphieunhap_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_chitietphieunhap
    ADD CONSTRAINT cuahang_chitietphieunhap_pkey PRIMARY KEY (id);


--
-- TOC entry 5975 (class 2606 OID 25904)
-- Name: cuahang_chitietphieuxuat cuahang_chitietphieuxuat_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_chitietphieuxuat
    ADD CONSTRAINT cuahang_chitietphieuxuat_pkey PRIMARY KEY (id);


--
-- TOC entry 5927 (class 2606 OID 17672)
-- Name: cuahang_cuahang cuahang_cuahang_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_cuahang
    ADD CONSTRAINT cuahang_cuahang_pkey PRIMARY KEY (id);


--
-- TOC entry 5938 (class 2606 OID 25698)
-- Name: cuahang_danhgia cuahang_danhgia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_danhgia
    ADD CONSTRAINT cuahang_danhgia_pkey PRIMARY KEY (id);


--
-- TOC entry 5956 (class 2606 OID 25795)
-- Name: cuahang_dinhmuc cuahang_dinhmuc_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_dinhmuc
    ADD CONSTRAINT cuahang_dinhmuc_pkey PRIMARY KEY (id);


--
-- TOC entry 5944 (class 2606 OID 25723)
-- Name: cuahang_donhang cuahang_donhang_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_donhang
    ADD CONSTRAINT cuahang_donhang_pkey PRIMARY KEY (id);


--
-- TOC entry 5949 (class 2606 OID 25764)
-- Name: cuahang_kho cuahang_kho_cua_hang_id_vat_tu_id_e073e236_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_kho
    ADD CONSTRAINT cuahang_kho_cua_hang_id_vat_tu_id_e073e236_uniq UNIQUE (cua_hang_id, vat_tu_id);


--
-- TOC entry 5951 (class 2606 OID 25762)
-- Name: cuahang_kho cuahang_kho_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_kho
    ADD CONSTRAINT cuahang_kho_pkey PRIMARY KEY (id);


--
-- TOC entry 5935 (class 2606 OID 25679)
-- Name: cuahang_nhanvien cuahang_nhanvien_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_nhanvien
    ADD CONSTRAINT cuahang_nhanvien_pkey PRIMARY KEY (id);


--
-- TOC entry 5965 (class 2606 OID 25851)
-- Name: cuahang_phieunhapkho cuahang_phieunhapkho_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_phieunhapkho
    ADD CONSTRAINT cuahang_phieunhapkho_pkey PRIMARY KEY (id);


--
-- TOC entry 5972 (class 2606 OID 25894)
-- Name: cuahang_phieuxuatkho cuahang_phieuxuatkho_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_phieuxuatkho
    ADD CONSTRAINT cuahang_phieuxuatkho_pkey PRIMARY KEY (id);


--
-- TOC entry 5954 (class 2606 OID 25785)
-- Name: cuahang_sanpham cuahang_sanpham_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_sanpham
    ADD CONSTRAINT cuahang_sanpham_pkey PRIMARY KEY (id);


--
-- TOC entry 5946 (class 2606 OID 25751)
-- Name: cuahang_vattu cuahang_vattu_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_vattu
    ADD CONSTRAINT cuahang_vattu_pkey PRIMARY KEY (id);


--
-- TOC entry 5924 (class 2606 OID 17633)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 5886 (class 2606 OID 17500)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 5888 (class 2606 OID 17498)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 5884 (class 2606 OID 17488)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 5931 (class 2606 OID 17683)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 5941 (class 2606 OID 25700)
-- Name: cuahang_danhgia unique_user_store_review; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_danhgia
    ADD CONSTRAINT unique_user_store_review UNIQUE (user_id, cua_hang_id);


--
-- TOC entry 5894 (class 1259 OID 17657)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 5899 (class 1259 OID 17588)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 5902 (class 1259 OID 17589)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 5889 (class 1259 OID 17574)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 5910 (class 1259 OID 17604)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 5913 (class 1259 OID 17603)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 5916 (class 1259 OID 17618)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 5919 (class 1259 OID 17617)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 5907 (class 1259 OID 17650)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 5959 (class 1259 OID 25835)
-- Name: cuahang_chitietdonhang_don_hang_id_93d82285; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuahang_chitietdonhang_don_hang_id_93d82285 ON public.cuahang_chitietdonhang USING btree (don_hang_id);


--
-- TOC entry 5962 (class 1259 OID 25836)
-- Name: cuahang_chitietdonhang_san_pham_id_91cf68f0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuahang_chitietdonhang_san_pham_id_91cf68f0 ON public.cuahang_chitietdonhang USING btree (san_pham_id);


--
-- TOC entry 5966 (class 1259 OID 25880)
-- Name: cuahang_chitietphieunhap_phieu_nhap_id_ecdcb70b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuahang_chitietphieunhap_phieu_nhap_id_ecdcb70b ON public.cuahang_chitietphieunhap USING btree (phieu_nhap_id);


--
-- TOC entry 5969 (class 1259 OID 25879)
-- Name: cuahang_chitietphieunhap_vat_tu_id_6e2db5a0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuahang_chitietphieunhap_vat_tu_id_6e2db5a0 ON public.cuahang_chitietphieunhap USING btree (vat_tu_id);


--
-- TOC entry 5973 (class 1259 OID 25922)
-- Name: cuahang_chitietphieuxuat_phieu_xuat_id_65ee599e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuahang_chitietphieuxuat_phieu_xuat_id_65ee599e ON public.cuahang_chitietphieuxuat USING btree (phieu_xuat_id);


--
-- TOC entry 5976 (class 1259 OID 25921)
-- Name: cuahang_chitietphieuxuat_vat_tu_id_76f11248; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuahang_chitietphieuxuat_vat_tu_id_76f11248 ON public.cuahang_chitietphieuxuat USING btree (vat_tu_id);


--
-- TOC entry 5928 (class 1259 OID 17673)
-- Name: cuahang_cuahang_vi_tri_8160a497_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuahang_cuahang_vi_tri_8160a497_id ON public.cuahang_cuahang USING gist (vi_tri);


--
-- TOC entry 5936 (class 1259 OID 25711)
-- Name: cuahang_danhgia_cua_hang_id_401b3f84; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuahang_danhgia_cua_hang_id_401b3f84 ON public.cuahang_danhgia USING btree (cua_hang_id);


--
-- TOC entry 5939 (class 1259 OID 25712)
-- Name: cuahang_danhgia_user_id_aa6dd0c9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuahang_danhgia_user_id_aa6dd0c9 ON public.cuahang_danhgia USING btree (user_id);


--
-- TOC entry 5957 (class 1259 OID 25812)
-- Name: cuahang_dinhmuc_san_pham_id_4dfbb962; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuahang_dinhmuc_san_pham_id_4dfbb962 ON public.cuahang_dinhmuc USING btree (san_pham_id);


--
-- TOC entry 5958 (class 1259 OID 25811)
-- Name: cuahang_dinhmuc_vat_tu_id_6ae956da; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuahang_dinhmuc_vat_tu_id_6ae956da ON public.cuahang_dinhmuc USING btree (vat_tu_id);


--
-- TOC entry 5942 (class 1259 OID 25729)
-- Name: cuahang_donhang_cua_hang_id_0ad9ebff; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuahang_donhang_cua_hang_id_0ad9ebff ON public.cuahang_donhang USING btree (cua_hang_id);


--
-- TOC entry 5947 (class 1259 OID 25775)
-- Name: cuahang_kho_cua_hang_id_8d069cef; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuahang_kho_cua_hang_id_8d069cef ON public.cuahang_kho USING btree (cua_hang_id);


--
-- TOC entry 5952 (class 1259 OID 25776)
-- Name: cuahang_kho_vat_tu_id_86ccd2d8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuahang_kho_vat_tu_id_86ccd2d8 ON public.cuahang_kho USING btree (vat_tu_id);


--
-- TOC entry 5933 (class 1259 OID 25685)
-- Name: cuahang_nhanvien_cua_hang_id_003aa626; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuahang_nhanvien_cua_hang_id_003aa626 ON public.cuahang_nhanvien USING btree (cua_hang_id);


--
-- TOC entry 5963 (class 1259 OID 25868)
-- Name: cuahang_phieunhapkho_cua_hang_id_1c0aeb75; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuahang_phieunhapkho_cua_hang_id_1c0aeb75 ON public.cuahang_phieunhapkho USING btree (cua_hang_id);


--
-- TOC entry 5970 (class 1259 OID 25910)
-- Name: cuahang_phieuxuatkho_cua_hang_id_06db9863; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuahang_phieuxuatkho_cua_hang_id_06db9863 ON public.cuahang_phieuxuatkho USING btree (cua_hang_id);


--
-- TOC entry 5922 (class 1259 OID 17644)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 5925 (class 1259 OID 17645)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 5929 (class 1259 OID 17685)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 5932 (class 1259 OID 17684)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 5978 (class 2606 OID 17583)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5979 (class 2606 OID 17578)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5977 (class 2606 OID 17569)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5980 (class 2606 OID 17598)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5981 (class 2606 OID 17593)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5982 (class 2606 OID 17612)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5983 (class 2606 OID 17607)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5994 (class 2606 OID 25825)
-- Name: cuahang_chitietdonhang cuahang_chitietdonha_don_hang_id_93d82285_fk_cuahang_d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_chitietdonhang
    ADD CONSTRAINT cuahang_chitietdonha_don_hang_id_93d82285_fk_cuahang_d FOREIGN KEY (don_hang_id) REFERENCES public.cuahang_donhang(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5995 (class 2606 OID 25830)
-- Name: cuahang_chitietdonhang cuahang_chitietdonha_san_pham_id_91cf68f0_fk_cuahang_s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_chitietdonhang
    ADD CONSTRAINT cuahang_chitietdonha_san_pham_id_91cf68f0_fk_cuahang_s FOREIGN KEY (san_pham_id) REFERENCES public.cuahang_sanpham(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5997 (class 2606 OID 25874)
-- Name: cuahang_chitietphieunhap cuahang_chitietphieu_phieu_nhap_id_ecdcb70b_fk_cuahang_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_chitietphieunhap
    ADD CONSTRAINT cuahang_chitietphieu_phieu_nhap_id_ecdcb70b_fk_cuahang_p FOREIGN KEY (phieu_nhap_id) REFERENCES public.cuahang_phieunhapkho(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6000 (class 2606 OID 25916)
-- Name: cuahang_chitietphieuxuat cuahang_chitietphieu_phieu_xuat_id_65ee599e_fk_cuahang_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_chitietphieuxuat
    ADD CONSTRAINT cuahang_chitietphieu_phieu_xuat_id_65ee599e_fk_cuahang_p FOREIGN KEY (phieu_xuat_id) REFERENCES public.cuahang_phieuxuatkho(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5998 (class 2606 OID 25869)
-- Name: cuahang_chitietphieunhap cuahang_chitietphieunhap_vat_tu_id_6e2db5a0_fk_cuahang_vattu_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_chitietphieunhap
    ADD CONSTRAINT cuahang_chitietphieunhap_vat_tu_id_6e2db5a0_fk_cuahang_vattu_id FOREIGN KEY (vat_tu_id) REFERENCES public.cuahang_vattu(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6001 (class 2606 OID 25911)
-- Name: cuahang_chitietphieuxuat cuahang_chitietphieuxuat_vat_tu_id_76f11248_fk_cuahang_vattu_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_chitietphieuxuat
    ADD CONSTRAINT cuahang_chitietphieuxuat_vat_tu_id_76f11248_fk_cuahang_vattu_id FOREIGN KEY (vat_tu_id) REFERENCES public.cuahang_vattu(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5987 (class 2606 OID 25701)
-- Name: cuahang_danhgia cuahang_danhgia_cua_hang_id_401b3f84_fk_cuahang_cuahang_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_danhgia
    ADD CONSTRAINT cuahang_danhgia_cua_hang_id_401b3f84_fk_cuahang_cuahang_id FOREIGN KEY (cua_hang_id) REFERENCES public.cuahang_cuahang(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5988 (class 2606 OID 25706)
-- Name: cuahang_danhgia cuahang_danhgia_user_id_aa6dd0c9_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_danhgia
    ADD CONSTRAINT cuahang_danhgia_user_id_aa6dd0c9_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5992 (class 2606 OID 25806)
-- Name: cuahang_dinhmuc cuahang_dinhmuc_san_pham_id_4dfbb962_fk_cuahang_sanpham_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_dinhmuc
    ADD CONSTRAINT cuahang_dinhmuc_san_pham_id_4dfbb962_fk_cuahang_sanpham_id FOREIGN KEY (san_pham_id) REFERENCES public.cuahang_sanpham(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5993 (class 2606 OID 25801)
-- Name: cuahang_dinhmuc cuahang_dinhmuc_vat_tu_id_6ae956da_fk_cuahang_vattu_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_dinhmuc
    ADD CONSTRAINT cuahang_dinhmuc_vat_tu_id_6ae956da_fk_cuahang_vattu_id FOREIGN KEY (vat_tu_id) REFERENCES public.cuahang_vattu(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5989 (class 2606 OID 25724)
-- Name: cuahang_donhang cuahang_donhang_cua_hang_id_0ad9ebff_fk_cuahang_cuahang_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_donhang
    ADD CONSTRAINT cuahang_donhang_cua_hang_id_0ad9ebff_fk_cuahang_cuahang_id FOREIGN KEY (cua_hang_id) REFERENCES public.cuahang_cuahang(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5990 (class 2606 OID 25765)
-- Name: cuahang_kho cuahang_kho_cua_hang_id_8d069cef_fk_cuahang_cuahang_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_kho
    ADD CONSTRAINT cuahang_kho_cua_hang_id_8d069cef_fk_cuahang_cuahang_id FOREIGN KEY (cua_hang_id) REFERENCES public.cuahang_cuahang(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5991 (class 2606 OID 25770)
-- Name: cuahang_kho cuahang_kho_vat_tu_id_86ccd2d8_fk_cuahang_vattu_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_kho
    ADD CONSTRAINT cuahang_kho_vat_tu_id_86ccd2d8_fk_cuahang_vattu_id FOREIGN KEY (vat_tu_id) REFERENCES public.cuahang_vattu(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5986 (class 2606 OID 25680)
-- Name: cuahang_nhanvien cuahang_nhanvien_cua_hang_id_003aa626_fk_cuahang_cuahang_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_nhanvien
    ADD CONSTRAINT cuahang_nhanvien_cua_hang_id_003aa626_fk_cuahang_cuahang_id FOREIGN KEY (cua_hang_id) REFERENCES public.cuahang_cuahang(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5996 (class 2606 OID 25863)
-- Name: cuahang_phieunhapkho cuahang_phieunhapkho_cua_hang_id_1c0aeb75_fk_cuahang_cuahang_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_phieunhapkho
    ADD CONSTRAINT cuahang_phieunhapkho_cua_hang_id_1c0aeb75_fk_cuahang_cuahang_id FOREIGN KEY (cua_hang_id) REFERENCES public.cuahang_cuahang(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5999 (class 2606 OID 25905)
-- Name: cuahang_phieuxuatkho cuahang_phieuxuatkho_cua_hang_id_06db9863_fk_cuahang_cuahang_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuahang_phieuxuatkho
    ADD CONSTRAINT cuahang_phieuxuatkho_cua_hang_id_06db9863_fk_cuahang_cuahang_id FOREIGN KEY (cua_hang_id) REFERENCES public.cuahang_cuahang(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5984 (class 2606 OID 17634)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5985 (class 2606 OID 17639)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2026-05-04 15:48:44

--
-- PostgreSQL database dump complete
--

\unrestrict FNMjS8MMCePrYgKwqJNS658sGBmFC8JdejSZQ5OUtZ22oECrSUm5XJ3ZKQJPSI6

