# Generated by Django 6.0.2 on 2026-02-04 03:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_quan', models.CharField(max_length=100, verbose_name='Tên Quán')),
                ('dia_chi', models.CharField(max_length=200, verbose_name='Địa chỉ')),
                ('vi_tri', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Vị trí')),
                ('ban_kinh', models.FloatField(default=5.0, verbose_name='Bán kính ship (km)')),
            ],
        ),
    ]
